from colorama import Fore, Back

BLACK = Fore.BLACK
RED = Fore.RED
GREEN = Fore.GREEN
YELLOW = Fore.YELLOW
BLUE = Fore.BLUE
MAGENTA = Fore.MAGENTA
CYAN = Fore.CYAN
WHITE = Fore.WHITE
LIGHTBLACK = Fore.LIGHTBLACK_EX
LIGHTRED = Fore.LIGHTRED_EX
LIGHTGREEN = Fore.LIGHTGREEN_EX
LIGHTYELLOW = Fore.LIGHTYELLOW_EX
LIGHTBLUE = Fore.LIGHTBLUE_EX
LIGHTMAGENTA = Fore.LIGHTMAGENTA_EX
LIGHTCYAN = Fore.LIGHTCYAN_EX
LIGHTWHITE = Fore.LIGHTWHITE_EX

BLACK_BACK = Back.BLACK
RED_BACK = Back.RED
GREEN_BACK = Back.GREEN
YELLOW_BACK = Back.YELLOW
BLUE_BACK = Back.BLUE
MAGENTA_BACK = Back.MAGENTA
CYAN_BACK = Back.CYAN
WHITE_BACK = Back.WHITE
