class TeamLookupException(Exception): ...


class DuplicateTeamNameFoundException(TeamLookupException): ...


class TeamNotFoundException(TeamLookupException): ...


class TeamMemberNotUniqueException(Exception): ...
